######################################################################
#
# File name : IR_tb_wave.do
# Created on: Mon Jun 27 09:46:32 +0200 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
