######################################################################
#
# File name : IR_tb.udo
# Created on: Mon Jun 27 09:46:32 +0200 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
