######################################################################
#
# File name : IR_tb_elaborate.do
# Created on: Mon Jun 27 09:46:20 +0200 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
C:\\questasim64_10.6c\\win64\\vopt -64 +acc=npr -L fifo_generator_v13_2_3 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm -work xil_defaultlib xil_defaultlib.IR_tb xil_defaultlib.glbl -o IR_tb_opt

quit -force
