######################################################################
#
# File name : IR_tb_compile.do
# Created on: Mon Jun 27 09:46:10 +0200 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
C:\\questasim64_10.6c\\win64\\vlib questa_lib/work
C:\\questasim64_10.6c\\win64\\vlib questa_lib/msim

C:\\questasim64_10.6c\\win64\\vlib questa_lib/msim/xil_defaultlib

C:\\questasim64_10.6c\\win64\\vmap xil_defaultlib questa_lib/msim/xil_defaultlib

C:\\questasim64_10.6c\\win64\\vlog -64 -incr -work xil_defaultlib  \
"../../../../IR_simulations.ip_user_files/ip/ir_fifo/sim/ir_fifo.v" \

C:\\questasim64_10.6c\\win64\\vcom -64 -93 -work xil_defaultlib  \
"../../../../../common_logic/RTL/Trigger_class_record/buffer_fifo.vhd" \
"../../../../../common_logic/RTL/Interaction_record_zerosuppr/top_ir_statemachine.vhd" \
"../../../../../common_logic/RTL/Interaction_record_zerosuppr/ir_statemachine.vhd" \
"../../../../../common_logic/RTL/Interaction_record_zerosuppr/packer_ir2.vhd" \
"../../../../../common_logic/RTL/Trigger_class_record/prsg_tcr.vhd" \
"../../../../../common_logic/Simulations/Interaction_record/ir_tb.vhd" \

# compile glbl module
C:\\questasim64_10.6c\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

